# Generated by Django 4.2 on 2026-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area_sqft', models.PositiveIntegerField()),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('penthouse', 'Penthouse'), ('house', 'House'), ('loft', 'Loft'), ('estate', 'Estate'), ('home', 'Home'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment')], max_length=20)),
                ('status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold')], default='for_sale', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('amenities', models.JSONField(default=list)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('listing_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
